<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hanhua Zhu">
<meta name="dcterms.date" content="2025-05-07">

<title>Poisson Regression Examples – hanhuazhu’s website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-226bd0f977fa82dfae4534cac220d79a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2d3a5f678c659c6d9658e8627949fb9f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">hanhuazhu’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">My Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#blueprinty-case-study" id="toc-blueprinty-case-study" class="nav-link active" data-scroll-target="#blueprinty-case-study">Blueprinty Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  </ul></li>
  <li><a href="#differences-in-firm-characteristics-by-customer-status" id="toc-differences-in-firm-characteristics-by-customer-status" class="nav-link" data-scroll-target="#differences-in-firm-characteristics-by-customer-status">Differences in Firm Characteristics by Customer Status</a>
  <ul class="collapse">
  <li><a href="#estimation-of-simple-poisson-model" id="toc-estimation-of-simple-poisson-model" class="nav-link" data-scroll-target="#estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</a></li>
  <li><a href="#coding-the-log-likelihood-function" id="toc-coding-the-log-likelihood-function" class="nav-link" data-scroll-target="#coding-the-log-likelihood-function">Coding the Log-Likelihood Function</a></li>
  <li><a href="#log-likelihood-over-a-range-of-λ-values" id="toc-log-likelihood-over-a-range-of-λ-values" class="nav-link" data-scroll-target="#log-likelihood-over-a-range-of-λ-values">Log-Likelihood over a Range of λ Values</a></li>
  <li><a href="#finding-the-mle-of-λ-using-optimization" id="toc-finding-the-mle-of-λ-using-optimization" class="nav-link" data-scroll-target="#finding-the-mle-of-λ-using-optimization">Finding the MLE of λ Using Optimization</a></li>
  <li><a href="#estimation-of-poisson-regression-model" id="toc-estimation-of-poisson-regression-model" class="nav-link" data-scroll-target="#estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</a></li>
  <li><a href="#defining-the-poisson-regression-log-likelihood" id="toc-defining-the-poisson-regression-log-likelihood" class="nav-link" data-scroll-target="#defining-the-poisson-regression-log-likelihood">Defining the Poisson Regression Log-Likelihood</a></li>
  <li><a href="#estimating-a-poisson-regression-model-with-statsmodels" id="toc-estimating-a-poisson-regression-model-with-statsmodels" class="nav-link" data-scroll-target="#estimating-a-poisson-regression-model-with-statsmodels">Estimating a Poisson Regression Model with <code>statsmodels</code></a></li>
  <li><a href="#verifying-results-using-statsmodels.glm" id="toc-verifying-results-using-statsmodels.glm" class="nav-link" data-scroll-target="#verifying-results-using-statsmodels.glm">Verifying Results Using <code>statsmodels.GLM</code></a></li>
  <li><a href="#simulated-impact-of-blueprintys-software" id="toc-simulated-impact-of-blueprintys-software" class="nav-link" data-scroll-target="#simulated-impact-of-blueprintys-software">Simulated Impact of Blueprinty’s Software</a></li>
  </ul></li>
  <li><a href="#airbnb-case-study" id="toc-airbnb-case-study" class="nav-link" data-scroll-target="#airbnb-case-study">AirBnB Case Study</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1">Introduction</a></li>
  </ul></li>
  <li><a href="#modeling-airbnb-reviews" id="toc-modeling-airbnb-reviews" class="nav-link" data-scroll-target="#modeling-airbnb-reviews">Modeling Airbnb Reviews</a>
  <ul class="collapse">
  <li><a href="#data-cleaning-and-exploration" id="toc-data-cleaning-and-exploration" class="nav-link" data-scroll-target="#data-cleaning-and-exploration">1. Data Cleaning and Exploration</a></li>
  <li><a href="#poisson-regression-model" id="toc-poisson-regression-model" class="nav-link" data-scroll-target="#poisson-regression-model">2. Poisson Regression Model</a></li>
  <li><a href="#interpretation-of-results" id="toc-interpretation-of-results" class="nav-link" data-scroll-target="#interpretation-of-results">3. Interpretation of Results</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression Examples</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hanhua Zhu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 7, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="blueprinty-case-study" class="level2">
<h2 class="anchored" data-anchor-id="blueprinty-case-study">Blueprinty Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Blueprinty is a small firm that makes software for developing blueprints specifically for submitting patent applications to the US patent office. Their marketing team would like to make the claim that patent applicants using Blueprinty’s software are more successful in getting their patent applications approved. Ideal data to study such an effect might include the success rate of patent applications before using Blueprinty’s software and after using it. Unfortunately, such data is not available.</p>
<p>However, Blueprinty has collected data on 1,500 mature (non-startup) engineering firms. The data include each firm’s number of patents awarded over the last 5 years, regional location, age since incorporation, and whether or not the firm uses Blueprinty’s software. The marketing team would like to use this data to make the claim that firms using Blueprinty’s software are more successful in getting their patent applications approved.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>We begin by loading the dataset containing information on engineering firms and their patenting activity. This includes whether or not a firm uses Blueprinty’s software.</p>
<div id="9b6c8d3f" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">patents</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">age</th>
<th data-quarto-table-cell-role="th">iscustomer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>Midwest</td>
<td>32.5</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>3</td>
<td>Southwest</td>
<td>37.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>4</td>
<td>Northwest</td>
<td>27.0</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>3</td>
<td>Northeast</td>
<td>24.5</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>3</td>
<td>Southwest</td>
<td>37.0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The first few rows of the dataset show each firm’s number of patents, regional location, age, and whether they are a Blueprinty customer. We see a mix of customer (<code>iscustomer = 1</code>) and non-customer firms, with patent counts ranging from 0 to 4. Firm ages vary from around 24 to 38 years, and regions span categories like Midwest and Southwest. These observations suggest the data is well-structured for count-based modeling and that customer status, region, and firm age may all influence patenting outcomes.</p>
<p><em>todo: Compare histograms and means of number of patents by customer status. What do you observe?</em> ## Patent Counts by Customer Status</p>
<p>To understand whether firms using Blueprinty’s software tend to receive more patents, we examine the distribution of patent counts by customer status. The plot below shows histograms for customers and non-customers side by side, and the table reports the average number of patents for each group.</p>
<div id="0d52d09b" class="cell" data-message="false" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-3-output-1.png" width="752" height="464" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The histogram above shows the distribution of patent counts for firms that do and do not use Blueprinty’s software. While the majority of both groups have relatively few patents, we observe that Blueprinty customers are more likely to appear in higher patent count categories (e.g., 5 or more patents). In contrast, non-customers dominate the lower count bins (0–3 patents). This suggests that firms using Blueprinty’s software may be associated with higher patenting activity, though further analysis is needed to account for other factors like firm age and region.</p>
<div id="e5ec4070" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">iscustomer</th>
<th data-quarto-table-cell-role="th">Average Number of Patents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>3.473013</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>1</td>
<td>4.133056</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>On average, Blueprinty customers have approximately 0.66 more patents than non-customers. While this difference is modest, it suggests a positive association between using the software and patenting activity. This pattern aligns with what we observed in the histogram and sets the stage for more rigorous modeling using Poisson regression.</p>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in the age and regional location of customers vs non-customers.</p>
</section>
</section>
<section id="differences-in-firm-characteristics-by-customer-status" class="level2">
<h2 class="anchored" data-anchor-id="differences-in-firm-characteristics-by-customer-status">Differences in Firm Characteristics by Customer Status</h2>
<p>Blueprinty customers are not selected at random. It may be important to account for systematic differences in characteristics like region and firm age between customers and non-customers.</p>
<p>We begin by examining whether the age distribution differs by customer status, and then compare regional distributions.</p>
<div id="db872eab" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/n6/y_4fsn553lq6_fzmfb11cjth0000gn/T/ipykernel_61357/1514657809.py:6: FutureWarning:



Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-5-output-2.png" width="752" height="463" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The boxplot reveals that Blueprinty customers tend to be slightly younger than non-customer firms. While both groups share similar age ranges and interquartile spreads, the median firm age is lower among customers. This suggests that firm age may influence both software adoption and patenting behavior. As a result, it is important to control for age in subsequent modeling to ensure we isolate the effect of using Blueprinty’s software from differences attributable to firm maturity.</p>
<p>The table shows the proportion of Blueprinty customers and non-customers across different regions. Most regions — including the Midwest, Northwest, South, and Southwest — have a relatively low customer adoption rate (about 16–18%). However, the Northeast stands out: a majority of firms in this region (55%) are Blueprinty customers.</p>
<div id="fc483bd1" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">iscustomer</th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Midwest</td>
<td>0.83</td>
<td>0.17</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>0.45</td>
<td>0.55</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>0.84</td>
<td>0.16</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">South</td>
<td>0.82</td>
<td>0.18</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>0.82</td>
<td>0.18</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This regional disparity suggests that firms in the Northeast are significantly more likely to use Blueprinty’s software. As a result, region may confound the relationship between software usage and patent success, and it should be accounted for in any regression model to avoid biased estimates.</p>
<section id="estimation-of-simple-poisson-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h3>
<p>Since our outcome variable of interest can only be small integer values per a set unit of time, we can use a Poisson density to model the number of patents awarded to each engineering firm over the last 5 years. We start by estimating a simple Poisson model via Maximum Likelihood.</p>
<p><em>todo: Write down mathematically the likelihood for</em> <span class="math inline">\(Y \sim \text{Poisson}(\lambda)\)</span>. Note that <span class="math inline">\(f(Y|\lambda) = e^{-\lambda}\lambda^Y/Y!\)</span>. ### Poisson Likelihood Function</p>
<p>Let ( Y_i (_i) ), where ( _i ) is the expected number of patents for firm ( i ).</p>
<p>The probability mass function for a Poisson-distributed outcome is:</p>
<p>[ f(Y_i | _i) = ]</p>
<p>Assuming observations are independent across ( n ) firms, the <strong>likelihood function</strong> is:</p>
<p>[ () = _{i=1}^n ]</p>
<p>Taking the log gives the <strong>log-likelihood</strong>:</p>
<p>[ () = _{i=1}^n ( -_i + Y_i _i - Y_i! ) ]</p>
<p>In Poisson regression, we model ( _i = (X_i ) ), which ensures ( _i &gt; 0 ).</p>
</section>
<section id="coding-the-log-likelihood-function" class="level3">
<h3 class="anchored" data-anchor-id="coding-the-log-likelihood-function">Coding the Log-Likelihood Function</h3>
<p>We define the log-likelihood function for a Poisson model, where the outcome variable ( Y ) follows a Poisson distribution with mean ( ). This function will be useful for implementing MLE manually.</p>
<div id="27dd2b76" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglikelihood(lam, y):</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute the log-likelihood for Poisson-distributed outcomes.</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">    - lam: array-like of expected values (lambda_i)</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    - y: array-like of observed counts (Y_i)</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">    </span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co">    - total log-likelihood (float)</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.asarray(lam)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>lam <span class="op">+</span> y <span class="op">*</span> np.log(lam) <span class="op">-</span> np.log(np.math.factorial(y)))</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loglik</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>todo: Use your function to plot lambda on the horizontal axis and the likelihood (or log-likelihood) on the vertical axis for a range of lambdas (use the observed number of patents as the input for Y).</em></p>
</section>
<section id="log-likelihood-over-a-range-of-λ-values" class="level3">
<h3 class="anchored" data-anchor-id="log-likelihood-over-a-range-of-λ-values">Log-Likelihood over a Range of λ Values</h3>
<p>We use our Poisson log-likelihood function to evaluate how the likelihood changes over different values of λ. This helps us visualize the value of λ that best fits the observed number of patents.</p>
<div id="6ce92db7" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-8-output-1.png" width="753" height="464" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The plot above shows how the Poisson log-likelihood varies with different values of λ, which represents the expected number of patents per firm. The curve peaks around λ = 4, indicating that this value maximizes the likelihood of observing the data under a Poisson model. In other words, the value λ ≈ 4 is the maximum likelihood estimate (MLE) — it best fits the distribution of observed patent counts. Values of λ much smaller or larger result in significantly lower likelihoods, confirming that λ ≈ 4 provides the most plausible explanation for the data.</p>
<p><em>todo: If you’re feeling mathematical, take the first derivative of your likelihood or log-likelihood, set it equal to zero and solve for lambda. You will find lambda_mle is Ybar, which “feels right” because the mean of a Poisson distribution is lambda.</em> ### Deriving the MLE for λ in the Poisson Model</p>
<p>Let ( Y_1, Y_2, , Y_n ) be independent observations from a Poisson distribution with parameter ( ). The log-likelihood function is:</p>
<p>[ () = _{i=1}^n ( -+ Y_i - Y_i! ) ]</p>
<p>To find the maximum likelihood estimate (MLE), take the derivative with respect to ( ), set it to zero, and solve:</p>
<p>[ = _{i=1}^n ( -1 + ) = 0 ]</p>
<p>[ -n + _{i=1}^n Y_i = 0 ]</p>
<p>[ <em>{i=1}^n Y_i = n = </em>{i=1}^n Y_i = {Y} ]</p>
<p>So, the MLE of ( ) is simply the <strong>sample mean</strong> of the observed data:</p>
<p>[ _{} = {Y} ]</p>
<p>This result makes intuitive sense because the Poisson distribution has a single parameter, ( ), which represents both its <strong>mean and variance</strong>.</p>
<p><em>todo: Find the MLE by optimizing your likelihood function with optim() in R or sp.optimize() in Python.</em></p>
</section>
<section id="finding-the-mle-of-λ-using-optimization" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-mle-of-λ-using-optimization">Finding the MLE of λ Using Optimization</h3>
<p>To confirm our visual result and mathematical derivation, we numerically estimate the MLE of ( ) by maximizing the Poisson log-likelihood. Since most optimizers minimize functions, we minimize the <strong>negative log-likelihood</strong> using <code>scipy.optimize</code>.</p>
<div id="4534ef37" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize_scalar</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the negative log-likelihood function</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_loglik(lambda_val):</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>poisson_loglikelihood(lambda_val, y_observed)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Optimize using bounded scalar minimization</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> minimize_scalar(neg_loglik, bounds<span class="op">=</span>(<span class="fl">0.1</span>, <span class="dv">10</span>), method<span class="op">=</span><span class="st">'bounded'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the MLE</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>lambda_mle <span class="op">=</span> result.x</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>lambda_mle</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>3.6846662261327716</code></pre>
</div>
</div>
</section>
<section id="estimation-of-poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model">Estimation of Poisson Regression Model</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model such that <span class="math inline">\(Y_i = \text{Poisson}(\lambda_i)\)</span> where <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>. The interpretation is that the success rate of patent awards is not constant across all firms (<span class="math inline">\(\lambda\)</span>) but rather is a function of firm characteristics <span class="math inline">\(X_i\)</span>. Specifically, we will use the covariates age, age squared, region, and whether the firm is a customer of Blueprinty.</p>
</section>
<section id="defining-the-poisson-regression-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="defining-the-poisson-regression-log-likelihood">Defining the Poisson Regression Log-Likelihood</h3>
<p>In the Poisson regression model, each firm ( i ) has a rate ( _i = (X_i^) ), where ( X_i ) includes the firm’s age, age squared, region dummies, and customer status. We now define the log-likelihood function in terms of ( ) and ( X ).</p>
<div id="03f54f98" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_loglikelihood(beta, y, X):</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Compute the Poisson regression log-likelihood.</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">    - beta: array-like, shape (k,)</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">    - y: array-like, shape (n,)</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">    - X: array-like, shape (n, k)</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">    - log-likelihood (float)</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> np.asarray(beta)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.asarray(y)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.asarray(X)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    lambda_i <span class="op">=</span> np.exp(X <span class="op">@</span> beta)  <span class="co"># inverse link function</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> np.<span class="bu">sum</span>(<span class="op">-</span>lambda_i <span class="op">+</span> y <span class="op">*</span> np.log(lambda_i) <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loglik</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="estimating-a-poisson-regression-model-with-statsmodels" class="level3">
<h3 class="anchored" data-anchor-id="estimating-a-poisson-regression-model-with-statsmodels">Estimating a Poisson Regression Model with <code>statsmodels</code></h3>
<p>We now estimate the Poisson regression using <code>statsmodels</code>, which provides built-in handling of the link function, robust inference, and well-formatted output.</p>
<div id="959fb781" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create age^2 and region dummies</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age_squared"</span>] <span class="op">=</span> df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine predictors</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.concat([</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"age"</span>, <span class="st">"age_squared"</span>, <span class="st">"iscustomer"</span>]],</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    region_dummies</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)  <span class="co"># add intercept</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert both X and y to float arrays (guaranteed numeric)</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X.astype(<span class="bu">float</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"patents"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Poisson regression</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="op">=</span> sm.GLM(y, X, family<span class="op">=</span>sm.families.Poisson())</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>poisson_results <span class="op">=</span> poisson_model.fit()</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Show model summary</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>poisson_results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Generalized Linear Model Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>patents</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>1500</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>GLM</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>1492</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Model Family:</td>
<td>Poisson</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Link Function:</td>
<td>Log</td>
<td data-quarto-table-cell-role="th">Scale:</td>
<td>1.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>IRLS</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-3258.1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Deviance:</td>
<td>2143.3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:14:25</td>
<td data-quarto-table-cell-role="th">Pearson chi2:</td>
<td>2.07e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Iterations:</td>
<td>5</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ. (CS):</td>
<td>0.1360</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>-0.5089</td>
<td>0.183</td>
<td>-2.778</td>
<td>0.005</td>
<td>-0.868</td>
<td>-0.150</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">age</td>
<td>0.1486</td>
<td>0.014</td>
<td>10.716</td>
<td>0.000</td>
<td>0.121</td>
<td>0.176</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">age_squared</td>
<td>-0.0030</td>
<td>0.000</td>
<td>-11.513</td>
<td>0.000</td>
<td>-0.003</td>
<td>-0.002</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">iscustomer</td>
<td>0.2076</td>
<td>0.031</td>
<td>6.719</td>
<td>0.000</td>
<td>0.147</td>
<td>0.268</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>0.0292</td>
<td>0.044</td>
<td>0.669</td>
<td>0.504</td>
<td>-0.056</td>
<td>0.115</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>-0.0176</td>
<td>0.054</td>
<td>-0.327</td>
<td>0.744</td>
<td>-0.123</td>
<td>0.088</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">South</td>
<td>0.0566</td>
<td>0.053</td>
<td>1.074</td>
<td>0.283</td>
<td>-0.047</td>
<td>0.160</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>0.0506</td>
<td>0.047</td>
<td>1.072</td>
<td>0.284</td>
<td>-0.042</td>
<td>0.143</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="verifying-results-using-statsmodels.glm" class="level3">
<h3 class="anchored" data-anchor-id="verifying-results-using-statsmodels.glm">Verifying Results Using <code>statsmodels.GLM</code></h3>
<p>To verify our custom likelihood and optimization results, we fit the same Poisson regression model using the built-in <code>statsmodels.GLM()</code> function with the Poisson family. This method handles link functions and inference automatically, providing coefficient estimates and standard errors.</p>
<div id="59634b0c" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create age squared and dummy variables</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age_squared"</span>] <span class="op">=</span> df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the design matrix</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.concat([</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"age"</span>, <span class="st">"age_squared"</span>, <span class="st">"iscustomer"</span>]],</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    region_dummies</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)  <span class="co"># Add intercept</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to float (ensures all numeric types)</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X.astype(<span class="bu">float</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"patents"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Poisson model</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>poisson_model <span class="op">=</span> sm.GLM(y, X, family<span class="op">=</span>sm.families.Poisson())</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>poisson_results <span class="op">=</span> poisson_model.fit()</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>poisson_results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Generalized Linear Model Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>patents</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>1500</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>GLM</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>1492</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Model Family:</td>
<td>Poisson</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>7</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Link Function:</td>
<td>Log</td>
<td data-quarto-table-cell-role="th">Scale:</td>
<td>1.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>IRLS</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-3258.1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Deviance:</td>
<td>2143.3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:14:25</td>
<td data-quarto-table-cell-role="th">Pearson chi2:</td>
<td>2.07e+03</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Iterations:</td>
<td>5</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ. (CS):</td>
<td>0.1360</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>-0.5089</td>
<td>0.183</td>
<td>-2.778</td>
<td>0.005</td>
<td>-0.868</td>
<td>-0.150</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">age</td>
<td>0.1486</td>
<td>0.014</td>
<td>10.716</td>
<td>0.000</td>
<td>0.121</td>
<td>0.176</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">age_squared</td>
<td>-0.0030</td>
<td>0.000</td>
<td>-11.513</td>
<td>0.000</td>
<td>-0.003</td>
<td>-0.002</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">iscustomer</td>
<td>0.2076</td>
<td>0.031</td>
<td>6.719</td>
<td>0.000</td>
<td>0.147</td>
<td>0.268</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Northeast</td>
<td>0.0292</td>
<td>0.044</td>
<td>0.669</td>
<td>0.504</td>
<td>-0.056</td>
<td>0.115</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Northwest</td>
<td>-0.0176</td>
<td>0.054</td>
<td>-0.327</td>
<td>0.744</td>
<td>-0.123</td>
<td>0.088</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">South</td>
<td>0.0566</td>
<td>0.053</td>
<td>1.074</td>
<td>0.283</td>
<td>-0.047</td>
<td>0.160</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Southwest</td>
<td>0.0506</td>
<td>0.047</td>
<td>1.072</td>
<td>0.284</td>
<td>-0.042</td>
<td>0.143</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>he regression results provide strong evidence that using Blueprinty’s software is associated with an increase in the expected number of patents. The coefficient on iscustomer is 0.2076 and is statistically significant (p &lt; 0.001), implying that being a customer increases the log expected patent count. Exponentiating this coefficient (i.e., 𝑒 0.2076 ≈ 1.23 e 0.2076 ≈1.23) suggests that, all else equal, Blueprinty customers have about 23% more patents than non-customers.</p>
<p>Firm age is also significant: the positive coefficient on age and negative coefficient on age_squared indicate a concave (inverted-U) relationship between age and patent output — suggesting patent productivity increases with age, but at a decreasing rate.</p>
<p>Regional variables are not statistically significant, indicating no clear evidence that location alone explains differences in patenting after controlling for other factors.</p>
<p>Overall, the model supports Blueprinty’s claim that their customers are more successful in patenting, even when accounting for differences in firm age and location.</p>
<p><em>todo: What do you conclude about the effect of Blueprinty’s software on patent success? Because the beta coefficients are not directly interpretable, it may help to create two fake datasets: X_0 and X_1 where X_0 is the X data but with iscustomer=0 for every observation and X_1 is the X data but with iscustomer=1 for every observation. Then, use X_0 and your fitted model to get the vector of predicted number of patents (y_pred_0) for every firm in the dataset, and use X_1 to get Y_pred_1 for every firm. Then subtract y_pred_1 minus y_pred_0 and take the average of that vector of differences.</em></p>
</section>
<section id="simulated-impact-of-blueprintys-software" class="level3">
<h3 class="anchored" data-anchor-id="simulated-impact-of-blueprintys-software">Simulated Impact of Blueprinty’s Software</h3>
<p>We now simulate the impact of Blueprinty by predicting patent counts under two scenarios: (1) no firms use the software, and (2) all firms use the software. We then compute the average difference in predicted patents across all firms.</p>
<div id="f2dff4c1" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>0.792768071045253</code></pre>
</div>
</div>
<p>To assess the practical impact of Blueprinty’s software on patenting outcomes, we simulated two scenarios using our fitted Poisson regression model. In the first scenario, we predicted the number of patents for each firm assuming none used Blueprinty. In the second, we predicted patent counts assuming all firms were customers. The average difference between these two sets of predictions was approximately 0.79 patents per firm, indicating that Blueprinty’s software is associated with a meaningful increase in patenting success. This approach translates the regression results into an interpretable quantity and confirms that, on average, firms that use Blueprinty are expected to secure nearly one additional patent over five years compared to similar non-customers.</p>
</section>
</section>
<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction-1" class="level3">
<h3 class="anchored" data-anchor-id="introduction-1">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City. The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
<p><em>todo: Assume the number of reviews is a good proxy for the number of bookings. Perform some exploratory data analysis to get a feel for the data, handle or drop observations with missing values on relevant variables, build one or more models (e.g., a poisson regression model for the number of bookings as proxied by the number of reviews), and interpret model coefficients to describe variation in the number of reviews as a function of the variables provided.</em></p>
</section>
</section>
<section id="modeling-airbnb-reviews" class="level2">
<h2 class="anchored" data-anchor-id="modeling-airbnb-reviews">Modeling Airbnb Reviews</h2>
<p>We assume that the number of reviews is a good proxy for the number of bookings a listing receives. In this section, we conduct exploratory data analysis, prepare the dataset, fit a Poisson regression model, and interpret the model results.</p>
<section id="data-cleaning-and-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-exploration">1. Data Cleaning and Exploration</h3>
<p>We begin by selecting relevant variables for predicting the number of reviews. We drop any rows with missing values to ensure clean model fitting.</p>
<div id="d8d33a7b" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Airbnb dataset (adjust the path as needed)</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"/Users/hanhuazhu/Desktop/mywebsite/blog/project2/airbnb.csv"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview column names to confirm structure</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>df.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>Index(['Unnamed: 0', 'id', 'days', 'last_scraped', 'host_since', 'room_type',
       'bathrooms', 'bedrooms', 'price', 'number_of_reviews',
       'review_scores_cleanliness', 'review_scores_location',
       'review_scores_value', 'instant_bookable'],
      dtype='object')</code></pre>
</div>
</div>
<div id="2223cc16" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select relevant variables</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>airbnb <span class="op">=</span> df[[</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"number_of_reviews"</span>, <span class="st">"room_type"</span>, <span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"price"</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"review_scores_cleanliness"</span>, <span class="st">"review_scores_location"</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"review_scores_value"</span>, <span class="st">"instant_bookable"</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>]]</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop missing values</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>airbnb <span class="op">=</span> airbnb.dropna()</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display a summary of the cleaned data</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>airbnb.describe(include<span class="op">=</span><span class="st">"all"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">number_of_reviews</th>
<th data-quarto-table-cell-role="th">room_type</th>
<th data-quarto-table-cell-role="th">bathrooms</th>
<th data-quarto-table-cell-role="th">bedrooms</th>
<th data-quarto-table-cell-role="th">price</th>
<th data-quarto-table-cell-role="th">review_scores_cleanliness</th>
<th data-quarto-table-cell-role="th">review_scores_location</th>
<th data-quarto-table-cell-role="th">review_scores_value</th>
<th data-quarto-table-cell-role="th">instant_bookable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>30160.000000</td>
<td>30160</td>
<td>30160.000000</td>
<td>30160.000000</td>
<td>30160.000000</td>
<td>30160.000000</td>
<td>30160.000000</td>
<td>30160.000000</td>
<td>30160</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">unique</td>
<td>NaN</td>
<td>3</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">top</td>
<td>NaN</td>
<td>Entire home/apt</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>f</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>NaN</td>
<td>15543</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>24243</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mean</td>
<td>21.170889</td>
<td>NaN</td>
<td>1.122132</td>
<td>1.151459</td>
<td>140.206863</td>
<td>9.201724</td>
<td>9.415351</td>
<td>9.333952</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">std</td>
<td>32.007541</td>
<td>NaN</td>
<td>0.384916</td>
<td>0.699010</td>
<td>188.392314</td>
<td>1.114261</td>
<td>0.843185</td>
<td>0.900472</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">min</td>
<td>1.000000</td>
<td>NaN</td>
<td>0.000000</td>
<td>0.000000</td>
<td>10.000000</td>
<td>2.000000</td>
<td>2.000000</td>
<td>2.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25%</td>
<td>3.000000</td>
<td>NaN</td>
<td>1.000000</td>
<td>1.000000</td>
<td>70.000000</td>
<td>9.000000</td>
<td>9.000000</td>
<td>9.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">50%</td>
<td>8.000000</td>
<td>NaN</td>
<td>1.000000</td>
<td>1.000000</td>
<td>103.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">75%</td>
<td>26.000000</td>
<td>NaN</td>
<td>1.000000</td>
<td>1.000000</td>
<td>169.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">max</td>
<td>421.000000</td>
<td>NaN</td>
<td>6.000000</td>
<td>10.000000</td>
<td>10000.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>10.000000</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="poisson-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="poisson-regression-model">2. Poisson Regression Model</h3>
<p>We use Poisson regression to model the number of reviews as a function of listing features, assuming that reviews follow a Poisson distribution. We include dummy variables for categorical features and a constant term.</p>
<div id="9101d0df" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>dummies <span class="op">=</span> pd.get_dummies(airbnb[[<span class="st">"room_type"</span>, <span class="st">"instant_bookable"</span>]], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Build design matrix</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>X_airbnb <span class="op">=</span> pd.concat([</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    airbnb[[<span class="st">"bathrooms"</span>, <span class="st">"bedrooms"</span>, <span class="st">"price"</span>, </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">"review_scores_cleanliness"</span>, </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>            <span class="st">"review_scores_location"</span>, </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>            <span class="st">"review_scores_value"</span>]],</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    dummies</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>X_airbnb <span class="op">=</span> sm.add_constant(X_airbnb)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure all data are numeric</span></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>X_airbnb <span class="op">=</span> X_airbnb.astype(<span class="bu">float</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>y_airbnb <span class="op">=</span> airbnb[<span class="st">"number_of_reviews"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit Poisson regression</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>model_airbnb <span class="op">=</span> sm.GLM(y_airbnb, X_airbnb, family<span class="op">=</span>sm.families.Poisson()).fit()</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>model_airbnb.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Generalized Linear Model Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>number_of_reviews</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>30160</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>GLM</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>30150</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Model Family:</td>
<td>Poisson</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>9</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Link Function:</td>
<td>Log</td>
<td data-quarto-table-cell-role="th">Scale:</td>
<td>1.0000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>IRLS</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5.2900e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Deviance:</td>
<td>9.3653e+05</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:14:26</td>
<td data-quarto-table-cell-role="th">Pearson chi2:</td>
<td>1.41e+06</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Iterations:</td>
<td>6</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ. (CS):</td>
<td>0.5649</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">const</td>
<td>3.5725</td>
<td>0.016</td>
<td>223.215</td>
<td>0.000</td>
<td>3.541</td>
<td>3.604</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">bathrooms</td>
<td>-0.1240</td>
<td>0.004</td>
<td>-33.091</td>
<td>0.000</td>
<td>-0.131</td>
<td>-0.117</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">bedrooms</td>
<td>0.0749</td>
<td>0.002</td>
<td>37.698</td>
<td>0.000</td>
<td>0.071</td>
<td>0.079</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">price</td>
<td>-1.435e-05</td>
<td>8.3e-06</td>
<td>-1.729</td>
<td>0.084</td>
<td>-3.06e-05</td>
<td>1.92e-06</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_cleanliness</td>
<td>0.1132</td>
<td>0.001</td>
<td>75.820</td>
<td>0.000</td>
<td>0.110</td>
<td>0.116</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">review_scores_location</td>
<td>-0.0768</td>
<td>0.002</td>
<td>-47.796</td>
<td>0.000</td>
<td>-0.080</td>
<td>-0.074</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">review_scores_value</td>
<td>-0.0915</td>
<td>0.002</td>
<td>-50.902</td>
<td>0.000</td>
<td>-0.095</td>
<td>-0.088</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">room_type_Private room</td>
<td>-0.0145</td>
<td>0.003</td>
<td>-5.310</td>
<td>0.000</td>
<td>-0.020</td>
<td>-0.009</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">room_type_Shared room</td>
<td>-0.2519</td>
<td>0.009</td>
<td>-29.229</td>
<td>0.000</td>
<td>-0.269</td>
<td>-0.235</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">instant_bookable_t</td>
<td>0.3344</td>
<td>0.003</td>
<td>115.748</td>
<td>0.000</td>
<td>0.329</td>
<td>0.340</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>l_airbnb.summary() ```</p>
</section>
<section id="interpretation-of-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-results">3. Interpretation of Results</h3>
<p>The coefficients from the Poisson regression represent the log change in expected number of reviews per one-unit increase in each predictor. Exponentiating these values gives us approximate percentage changes. For example, the coefficient on instant_bookable_t is 0.3344, which implies that listings that are instantly bookable receive approximately 40% more reviews than those that are not ( 𝑒 0.3344 ≈ 1.40 e 0.3344 ≈1.40).</p>
<p>Several listing characteristics are significantly associated with review counts. Listings with more bedrooms are associated with more reviews, while more bathrooms are unexpectedly associated with fewer. Cleanliness scores are strongly and positively related to review volume, while location and value scores are negatively associated — possibly reflecting competitive pressures in highly rated areas.</p>
<p>Room type also plays a significant role. Compared to entire homes/apartments, private rooms receive slightly fewer reviews, while shared rooms see a substantially lower expected review count. Price has a small negative coefficient and is only marginally significant.</p>
<p>Overall, these results suggest that listing type, cleanliness, instant booking, and core features like bedrooms meaningfully affect how often a listing is booked (as proxied by reviews).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>