project:
  type: website
  output-dir: docs

website:
  title: "hanhuazhu's website"
navbar:
  left:
    - text: About
      href: index.qmd
    - text: Resume
      href: resume.qmd     
    - text: Projects
      href: blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true





