<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hanhua Zhu">
<meta name="dcterms.date" content="2025-04-22">

<title>A Replication of Karlan and List (2007) – hanhuazhu’s website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-226bd0f977fa82dfae4534cac220d79a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2d3a5f678c659c6d9658e8627949fb9f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">hanhuazhu’s website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">My Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  </ul></li>
  <li><a href="#description-1" id="toc-description-1" class="nav-link" data-scroll-target="#description-1">Description</a>
  <ul class="collapse">
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  <li><a href="#manual-t-test-results" id="toc-manual-t-test-results" class="nav-link" data-scroll-target="#manual-t-test-results">Manual T-Test Results</a></li>
  <li><a href="#linear-regression-results" id="toc-linear-regression-results" class="nav-link" data-scroll-target="#linear-regression-results">Linear Regression Results</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#charitable-contribution-made-1" id="toc-charitable-contribution-made-1" class="nav-link" data-scroll-target="#charitable-contribution-made-1">Charitable Contribution Made</a></li>
  <li><a href="#interpretation-of-experimental-results" id="toc-interpretation-of-experimental-results" class="nav-link" data-scroll-target="#interpretation-of-experimental-results">Interpretation of Experimental Results</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#differences-between-match-rates-1" id="toc-differences-between-match-rates-1" class="nav-link" data-scroll-target="#differences-between-match-rates-1">Differences between Match Rates</a></li>
  <li><a href="#t-tests-for-match-ratios" id="toc-t-tests-for-match-ratios" class="nav-link" data-scroll-target="#t-tests-for-match-ratios">T-tests for Match Ratios</a></li>
  <li><a href="#regression-on-match-ratio-categorical" id="toc-regression-on-match-ratio-categorical" class="nav-link" data-scroll-target="#regression-on-match-ratio-categorical">Regression on Match Ratio (Categorical)</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a>
  <ul class="collapse">
  <li><a href="#full-sample-regression" id="toc-full-sample-regression" class="nav-link" data-scroll-target="#full-sample-regression">Full Sample Regression</a></li>
  <li><a href="#regression-among-donors-only" id="toc-regression-among-donors-only" class="nav-link" data-scroll-target="#regression-among-donors-only">Regression Among Donors Only</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">Interpretation</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#law-of-large-numbers-1" id="toc-law-of-large-numbers-1" class="nav-link" data-scroll-target="#law-of-large-numbers-1">Law of Large Numbers</a></li>
  <li><a href="#law-of-large-numbers-2" id="toc-law-of-large-numbers-2" class="nav-link" data-scroll-target="#law-of-large-numbers-2">Law of Large Numbers</a></li>
  <li><a href="#law-of-large-numbers-3" id="toc-law-of-large-numbers-3" class="nav-link" data-scroll-target="#law-of-large-numbers-3">Law of Large Numbers</a></li>
  <li><a href="#law-of-large-numbers-convergence-of-mean-difference" id="toc-law-of-large-numbers-convergence-of-mean-difference" class="nav-link" data-scroll-target="#law-of-large-numbers-convergence-of-mean-difference">Law of Large Numbers: Convergence of Mean Difference</a></li>
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3">Interpretation</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  <li><a href="#interpretation-4" id="toc-interpretation-4" class="nav-link" data-scroll-target="#interpretation-4">Interpretation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hanhua Zhu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 22, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a large-scale natural field experiment to test the effectiveness of different fundraising strategies. They sent out over 50,000 fundraising letters to prior donors of a nonprofit organization, randomly assigning recipients to one of several treatment groups.</p>
<p>The experiment tested whether the presence of a matching donation offer (e.g., for every $1 donated, the organization receives $2, $3, or $4 total depending on the match ratio) would increase both the likelihood of giving and the amount donated. The matching ratios varied between 1:1, 2:1, and 3:1. In addition, the letters varied the maximum match amount (e.g., $25,000, $50,000, or $100,000) and the suggested donation amount, which was calculated based on each recipient’s highest prior donation.</p>
<p>Recipients were randomly assigned to treatment groups, making this a clean experimental design for causal inference. The primary outcomes were whether someone donated and how much they gave. These results help inform how nonprofits can design more effective fundraising campaigns.</p>
<p>The results were published in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>.</p>
<p>This project seeks to replicate some of their core findings using the original dataset and statistical methods.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<p>We load and explore the dataset from Karlan and List (2007).</p>
</section>
</section>
<section id="description-1" class="level2">
<h2 class="anchored" data-anchor-id="description-1">Description</h2>
<p>The dataset includes 50,083 observations, each representing a past donor who received a fundraising letter as part of a large-scale randomized field experiment. The dataset captures a wide range of information, including treatment assignments, donation outcomes, prior giving behavior, and demographic context.</p>
<p>There are 51 variables in total, which can be broadly grouped into the following categories: - <strong>Treatment indicators</strong>: such as <code>treatment</code>, <code>ratio2</code>, <code>ratio3</code>, <code>size25</code>, <code>size50</code>, <code>size100</code>, and <code>askd1</code>, which reflect match ratios, thresholds, and suggested donation amounts. - <strong>Outcome variables</strong>: including <code>gave</code> (binary indicator for donation) and <code>amount</code> (dollar amount donated). - <strong>Historical giving behavior</strong>: such as <code>hpa</code> (highest previous amount), <code>ltmedmra</code> (indicator for low prior donors), and <code>years</code> since the first donation. - <strong>Demographic and contextual features</strong>: such as <code>female</code>, <code>couple</code>, <code>median_hhincome</code>, <code>page18_39</code>, <code>pwhite</code>, and <code>pop_propurban</code>.</p>
<p>Most variables are either complete or have minimal missingness, and the data types are a mix of binary indicators, integers, floats, and categorical values. This structure makes the dataset well-suited for regression, simulation, and visualization tasks.</p>
<p>Summary statistics show that approximately <strong>66.7% of observations are in the treatment group</strong>, with <strong>33.3% in the control group</strong>, as expected from random assignment. The <code>gave</code> variable indicates that about <strong>2.06% of individuals donated</strong>, and the average donation (<code>amount</code>) across the full sample is <strong>$0.92</strong>, with some contributions reaching as high as <strong>$400</strong>. This reflects the typical skew in donation behavior: most individuals gave nothing, while a few gave large amounts.</p>
<p>The match ratio flags (<code>ratio2</code>, <code>ratio3</code>) suggest roughly <strong>equal allocation</strong> across the 1:1, 2:1, and 3:1 groups. Likewise, the match threshold indicators (<code>size25</code>, <code>size50</code>, <code>size100</code>, <code>sizeno</code>) are each present in about <strong>16.7%</strong> of the sample. Suggested donation framing variables (<code>askd1</code>, <code>askd2</code>, <code>askd3</code>) also appear to be evenly distributed, reinforcing that the experimental design was properly randomized.</p>
<p>The table below provides descriptions for key variables in the dataset.</p>
<p>#:::: {.callout-note collapse=“true”}</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>##</th>
<th>Variable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
<div id="9094d01a" class="cell" data-message="false" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">treatment</td>
<td>50083.0</td>
<td>0.666813</td>
<td>0.471357</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">control</td>
<td>50083.0</td>
<td>0.333187</td>
<td>0.471357</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ratio2</td>
<td>50083.0</td>
<td>0.222311</td>
<td>0.415803</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ratio3</td>
<td>50083.0</td>
<td>0.222211</td>
<td>0.415736</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">size25</td>
<td>50083.0</td>
<td>0.166723</td>
<td>0.372732</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">size50</td>
<td>50083.0</td>
<td>0.166623</td>
<td>0.372643</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">size100</td>
<td>50083.0</td>
<td>0.166723</td>
<td>0.372732</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">sizeno</td>
<td>50083.0</td>
<td>0.166743</td>
<td>0.372750</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">askd1</td>
<td>50083.0</td>
<td>0.222311</td>
<td>0.415803</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">askd2</td>
<td>50083.0</td>
<td>0.222291</td>
<td>0.415790</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">askd3</td>
<td>50083.0</td>
<td>0.222211</td>
<td>0.415736</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ask1</td>
<td>50083.0</td>
<td>71.501807</td>
<td>101.728936</td>
<td>25.000000</td>
<td>35.000000</td>
<td>45.000000</td>
<td>65.000000</td>
<td>1500.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ask2</td>
<td>50083.0</td>
<td>91.792724</td>
<td>127.252628</td>
<td>35.000000</td>
<td>45.000000</td>
<td>60.000000</td>
<td>85.000000</td>
<td>1875.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ask3</td>
<td>50083.0</td>
<td>111.046263</td>
<td>151.673562</td>
<td>50.000000</td>
<td>55.000000</td>
<td>70.000000</td>
<td>100.000000</td>
<td>2250.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">amount</td>
<td>50083.0</td>
<td>0.915694</td>
<td>8.707393</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>400.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">gave</td>
<td>50083.0</td>
<td>0.020646</td>
<td>0.142197</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">amountchange</td>
<td>50083.0</td>
<td>-52.672016</td>
<td>1267.097778</td>
<td>-200412.125000</td>
<td>-50.000000</td>
<td>-30.000000</td>
<td>-25.000000</td>
<td>275.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">hpa</td>
<td>50083.0</td>
<td>59.384975</td>
<td>71.179871</td>
<td>0.000000</td>
<td>30.000000</td>
<td>45.000000</td>
<td>60.000000</td>
<td>1000.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">ltmedmra</td>
<td>50083.0</td>
<td>0.493720</td>
<td>0.499966</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">freq</td>
<td>50083.0</td>
<td>8.039355</td>
<td>11.394454</td>
<td>0.000000</td>
<td>2.000000</td>
<td>4.000000</td>
<td>10.000000</td>
<td>218.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">years</td>
<td>50082.0</td>
<td>6.097540</td>
<td>5.503492</td>
<td>0.000000</td>
<td>2.000000</td>
<td>5.000000</td>
<td>9.000000</td>
<td>95.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">year5</td>
<td>50083.0</td>
<td>0.508815</td>
<td>0.499927</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">mrm2</td>
<td>50082.0</td>
<td>13.007268</td>
<td>12.081403</td>
<td>0.000000</td>
<td>4.000000</td>
<td>8.000000</td>
<td>19.000000</td>
<td>168.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">dormant</td>
<td>50083.0</td>
<td>0.523471</td>
<td>0.499454</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">female</td>
<td>48972.0</td>
<td>0.277669</td>
<td>0.447854</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">couple</td>
<td>48935.0</td>
<td>0.091897</td>
<td>0.288884</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">state50one</td>
<td>50083.0</td>
<td>0.000998</td>
<td>0.031581</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">nonlit</td>
<td>49631.0</td>
<td>2.473918</td>
<td>1.961528</td>
<td>0.000000</td>
<td>1.000000</td>
<td>3.000000</td>
<td>4.000000</td>
<td>6.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">cases</td>
<td>49631.0</td>
<td>1.499768</td>
<td>1.155140</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>2.000000</td>
<td>4.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">statecnt</td>
<td>50083.0</td>
<td>5.998820</td>
<td>5.745993</td>
<td>0.001995</td>
<td>1.833234</td>
<td>3.538799</td>
<td>9.607021</td>
<td>17.368841</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">stateresponse</td>
<td>50083.0</td>
<td>0.020627</td>
<td>0.005171</td>
<td>0.000000</td>
<td>0.018163</td>
<td>0.019710</td>
<td>0.023048</td>
<td>0.076923</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">stateresponset</td>
<td>50083.0</td>
<td>0.021989</td>
<td>0.006257</td>
<td>0.000000</td>
<td>0.018493</td>
<td>0.021697</td>
<td>0.024703</td>
<td>0.111111</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">stateresponsec</td>
<td>50080.0</td>
<td>0.017717</td>
<td>0.007516</td>
<td>0.000000</td>
<td>0.012862</td>
<td>0.019881</td>
<td>0.020806</td>
<td>0.052632</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">stateresponsetminc</td>
<td>50080.0</td>
<td>0.004273</td>
<td>0.009112</td>
<td>-0.047619</td>
<td>-0.001388</td>
<td>0.001779</td>
<td>0.010545</td>
<td>0.111111</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">perbush</td>
<td>50048.0</td>
<td>0.487940</td>
<td>0.078733</td>
<td>0.090909</td>
<td>0.444444</td>
<td>0.484848</td>
<td>0.525253</td>
<td>0.731959</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">close25</td>
<td>50048.0</td>
<td>0.185702</td>
<td>0.388870</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">red0</td>
<td>50048.0</td>
<td>0.404452</td>
<td>0.490791</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">blue0</td>
<td>50048.0</td>
<td>0.595548</td>
<td>0.490791</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">redcty</td>
<td>49978.0</td>
<td>0.510245</td>
<td>0.499900</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">bluecty</td>
<td>49978.0</td>
<td>0.488715</td>
<td>0.499878</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">pwhite</td>
<td>48217.0</td>
<td>0.819599</td>
<td>0.168560</td>
<td>0.009418</td>
<td>0.755845</td>
<td>0.872797</td>
<td>0.938827</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">pblack</td>
<td>48047.0</td>
<td>0.086710</td>
<td>0.135868</td>
<td>0.000000</td>
<td>0.014729</td>
<td>0.036554</td>
<td>0.090882</td>
<td>0.989622</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">page18_39</td>
<td>48217.0</td>
<td>0.321694</td>
<td>0.103039</td>
<td>0.000000</td>
<td>0.258311</td>
<td>0.305534</td>
<td>0.369132</td>
<td>0.997544</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">ave_hh_sz</td>
<td>48221.0</td>
<td>2.429012</td>
<td>0.378105</td>
<td>0.000000</td>
<td>2.210000</td>
<td>2.440000</td>
<td>2.660000</td>
<td>5.270000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">median_hhincome</td>
<td>48209.0</td>
<td>54815.700533</td>
<td>22027.316665</td>
<td>5000.000000</td>
<td>39181.000000</td>
<td>50673.000000</td>
<td>66005.000000</td>
<td>200001.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">powner</td>
<td>48214.0</td>
<td>0.669418</td>
<td>0.193405</td>
<td>0.000000</td>
<td>0.560222</td>
<td>0.712296</td>
<td>0.816798</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">psch_atlstba</td>
<td>48215.0</td>
<td>0.391661</td>
<td>0.186599</td>
<td>0.000000</td>
<td>0.235647</td>
<td>0.373744</td>
<td>0.530036</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">pop_propurban</td>
<td>48217.0</td>
<td>0.871968</td>
<td>0.258633</td>
<td>0.000000</td>
<td>0.884929</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="8704a58b" class="cell" data-message="false" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">treatment</th>
<th data-quarto-table-cell-role="th">control</th>
<th data-quarto-table-cell-role="th">ratio2</th>
<th data-quarto-table-cell-role="th">ratio3</th>
<th data-quarto-table-cell-role="th">size25</th>
<th data-quarto-table-cell-role="th">size50</th>
<th data-quarto-table-cell-role="th">size100</th>
<th data-quarto-table-cell-role="th">sizeno</th>
<th data-quarto-table-cell-role="th">askd1</th>
<th data-quarto-table-cell-role="th">askd2</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">redcty</th>
<th data-quarto-table-cell-role="th">bluecty</th>
<th data-quarto-table-cell-role="th">pwhite</th>
<th data-quarto-table-cell-role="th">pblack</th>
<th data-quarto-table-cell-role="th">page18_39</th>
<th data-quarto-table-cell-role="th">ave_hh_sz</th>
<th data-quarto-table-cell-role="th">median_hhincome</th>
<th data-quarto-table-cell-role="th">powner</th>
<th data-quarto-table-cell-role="th">psch_atlstba</th>
<th data-quarto-table-cell-role="th">pop_propurban</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">count</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>50083.000000</td>
<td>...</td>
<td>49978.000000</td>
<td>49978.000000</td>
<td>48217.000000</td>
<td>48047.000000</td>
<td>48217.000000</td>
<td>48221.000000</td>
<td>48209.000000</td>
<td>48214.000000</td>
<td>48215.000000</td>
<td>48217.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">mean</td>
<td>0.666813</td>
<td>0.333187</td>
<td>0.222311</td>
<td>0.222211</td>
<td>0.166723</td>
<td>0.166623</td>
<td>0.166723</td>
<td>0.166743</td>
<td>0.222311</td>
<td>0.222291</td>
<td>...</td>
<td>0.510245</td>
<td>0.488715</td>
<td>0.819599</td>
<td>0.086710</td>
<td>0.321694</td>
<td>2.429012</td>
<td>54815.700533</td>
<td>0.669418</td>
<td>0.391661</td>
<td>0.871968</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">std</td>
<td>0.471357</td>
<td>0.471357</td>
<td>0.415803</td>
<td>0.415736</td>
<td>0.372732</td>
<td>0.372643</td>
<td>0.372732</td>
<td>0.372750</td>
<td>0.415803</td>
<td>0.415790</td>
<td>...</td>
<td>0.499900</td>
<td>0.499878</td>
<td>0.168560</td>
<td>0.135868</td>
<td>0.103039</td>
<td>0.378105</td>
<td>22027.316665</td>
<td>0.193405</td>
<td>0.186599</td>
<td>0.258633</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">min</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.009418</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>5000.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">25%</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.755845</td>
<td>0.014729</td>
<td>0.258311</td>
<td>2.210000</td>
<td>39181.000000</td>
<td>0.560222</td>
<td>0.235647</td>
<td>0.884929</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">50%</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.872797</td>
<td>0.036554</td>
<td>0.305534</td>
<td>2.440000</td>
<td>50673.000000</td>
<td>0.712296</td>
<td>0.373744</td>
<td>1.000000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">75%</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>0.000000</td>
<td>...</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.938827</td>
<td>0.090882</td>
<td>0.369132</td>
<td>2.660000</td>
<td>66005.000000</td>
<td>0.816798</td>
<td>0.530036</td>
<td>1.000000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">max</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>...</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>0.989622</td>
<td>0.997544</td>
<td>5.270000</td>
<td>200001.000000</td>
<td>1.000000</td>
<td>1.000000</td>
<td>1.000000</td>
</tr>
</tbody>
</table>

<p>8 rows × 48 columns</p>
</div>
</div>
</div>
<p>::::</p>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another.</p>
<p>To assess whether the treatment was randomly assigned, I examine five pre-treatment covariates unrelated to the outcome: <code>years</code> (years since first donation), <code>female</code> (gender indicator), <code>couple</code> (marital status), <code>median_hhincome</code> (median household income by zip code), and <code>page18_39</code> (proportion aged 18–39 in the zip code). These are useful for balance testing because they should not be affected by treatment assignment and reflect characteristics likely observed before the intervention.</p>
<p>For each variable, I conduct:</p>
<ol type="1">
<li>A <strong>manual t-test</strong>, calculated using the following formula:</li>
</ol>
<p><span class="math display">\[
t = \frac{\bar{X}_{\text{treatment}} - \bar{X}_{\text{control}}}{\sqrt{\frac{s^2_{\text{treatment}}}{n_{\text{treatment}}} + \frac{s^2_{\text{control}}}{n_{\text{control}}}}}
\]</span></p>
<ol start="2" type="1">
<li>A <strong>linear regression</strong>, where the covariate is regressed on the treatment indicator:</li>
</ol>
<p><span class="math display">\[
\text{covariate}_i = \alpha + \beta \cdot \text{treatment}_i + \varepsilon_i
\]</span></p>
<p>The coefficient <span class="math inline">\(\beta\)</span> captures the estimated difference in means between groups.</p>
<hr>
</section>
<section id="manual-t-test-results" class="level3">
<h3 class="anchored" data-anchor-id="manual-t-test-results">Manual T-Test Results</h3>
<ul>
<li><code>years</code>: The t-statistic was <strong>-1.091</strong>, indicating no significant difference.</li>
<li><code>female</code>: The t-statistic was <strong>-1.754</strong>, just below conventional significance.</li>
<li><code>couple</code>: The t-statistic was <strong>-0.582</strong>, suggesting no group difference in relationship status.</li>
<li><code>median_hhincome</code>: The t-statistic was <strong>-0.743</strong>, showing no income-based imbalance.</li>
<li><code>page18_39</code>: The t-statistic was <strong>-0.124</strong>, indicating age composition is well balanced.</li>
</ul>
<hr>
</section>
<section id="linear-regression-results" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-results">Linear Regression Results</h3>
<p>Each covariate was also regressed on the treatment variable:</p>
<ul>
<li><code>years</code>: Coefficient = <strong>-0.058</strong>, p = <strong>0.270</strong></li>
<li><code>female</code>: Coefficient = <strong>-0.008</strong>, p = <strong>0.079</strong></li>
<li><code>couple</code>: Coefficient = <strong>-0.002</strong>, p = <strong>0.559</strong></li>
<li><code>median_hhincome</code>: Coefficient = <strong>-157.925</strong>, p = <strong>0.458</strong></li>
<li><code>page18_39</code>: Coefficient = <strong>~0.000</strong>, p = <strong>0.901</strong></li>
</ul>
<hr>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>Across all covariates, both the t-tests and linear regressions provide consistent evidence of <strong>no statistically significant differences</strong> between the treatment and control groups. The estimated coefficients are small, and all p-values exceed 0.05, supporting the assumption of balance under random assignment.</p>
<p>These results replicate the purpose of <strong>Table 1 in Karlan and List (2007)</strong>, which provides confidence that the estimated treatment effects are not confounded by observable pre-treatment characteristics.</p>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation.</p>
</section>
<section id="charitable-contribution-made-1" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made-1">Charitable Contribution Made</h3>
<p>We examine whether the treatment group had a higher donation rate compared to the control group.</p>
<div id="87128590" class="cell" data-message="false" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions (4)_files/figure-html/cell-5-output-1.png" width="606" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart above compares the average donation rates between individuals in the control group and those in the treatment group. The control group received a standard fundraising letter, while the treatment group received a letter that included a matching donation offer.</p>
<p>Although the overall donation rates are low in both groups, the treatment group shows a visibly higher proportion of individuals who donated. This difference, though modest, is consistent with the hypothesis that matching gifts encourage charitable giving. The visual evidence aligns with the statistical results from t-tests and regressions presented later in the analysis, and replicates the main findings of Karlan and List (2007), where even small psychological nudges—like a matching offer—can lead to meaningful behavioral changes.</p>
<section id="t-test-for-donation-rates" class="level4">
<h4 class="anchored" data-anchor-id="t-test-for-donation-rates">T-Test for Donation Rates</h4>
<p>This code performs an independent samples t-test to determine whether the mean donation rate (<code>gave</code>) differs significantly between the treatment and control groups. Since <code>gave</code> is a binary outcome indicating whether a donation was made, the test compares the proportion of donors across the two groups to assess the effect of receiving a matching donation offer.</p>
<div id="959d9b6d" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># T-test on binary outcome (gave)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>treat <span class="op">=</span> data[data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>control <span class="op">=</span> data[data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'gave'</span>]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>t_stat, p_val <span class="op">=</span> stats.ttest_ind(treat, control, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-test for 'gave':</span><span class="ch">\n</span><span class="ss">T-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.3f}</span><span class="ss">, p-value: </span><span class="sc">{</span>p_val<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-test for 'gave':
T-statistic: 3.209, p-value: 0.001</code></pre>
</div>
</div>
<p>The result of the t-test yields a t-statistic of 3.209 with a p-value of 0.001. This indicates a statistically significant difference in donation rates between the treatment and control groups at the 1% significance level. In other words, individuals who received a matching donation offer were significantly more likely to donate than those who did not, supporting the hypothesis that such offers increase giving behavior.</p>
<p>To complement the t-test, we estimate a simple ordinary least squares (OLS) regression to evaluate the effect of the treatment assignment on the probability of giving. The binary outcome variable <code>gave</code> is regressed on the treatment indicator, which equals 1 for those who received a matching donation offer and 0 for the control group.</p>
<p>This model can be interpreted as a comparison of group means, where the intercept represents the donation rate in the control group, and the treatment coefficient captures the average difference in donation rates between groups.</p>
<div id="064bca45" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bivariate OLS regression: gave ~ treatment</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">"gave ~ treatment"</span>, data<span class="op">=</span>data).fit()</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>gave</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>9.618</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.00193</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:39:02</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>26630.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>50083</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>-5.326e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>50081</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>-5.324e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>1</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>0.0179</td>
<td>0.001</td>
<td>16.225</td>
<td>0.000</td>
<td>0.016</td>
<td>0.020</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">treatment</td>
<td>0.0042</td>
<td>0.001</td>
<td>3.101</td>
<td>0.002</td>
<td>0.002</td>
<td>0.007</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>59814.280</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>2.005</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.000</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>4317152.727</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>6.740</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>46.440</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>3.23</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<p>The results confirm what we observed in the t-test. The coefficient on the <code>treatment</code> variable is <strong>0.0042</strong>, with a <strong>p-value of 0.002</strong>, indicating that the difference in donation rates between treatment and control is statistically significant at the 1% level.</p>
<p>This suggests that receiving a matching donation offer increased the likelihood of giving by approximately <strong>0.42 percentage points</strong>. While this effect may seem small in absolute terms, it is consistent with the behavioral insights from Karlan and List (2007): even modest framing changes like mentioning a match can lead to meaningful increases in donor participation.</p>
<div id="f23d3f2f" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probit regression: gave ~ treatment</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>probit_model <span class="op">=</span> smf.probit(<span class="st">"gave ~ treatment"</span>, data<span class="op">=</span>data).fit()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>probit_model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.100443
         Iterations 7</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="7">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Probit Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>gave</td>
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>50083</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>Probit</td>
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>50081</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>MLE</td>
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Pseudo R-squ.:</td>
<td>0.0009783</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:39:02</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5030.5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">converged:</td>
<td>True</td>
<td data-quarto-table-cell-role="th">LL-Null:</td>
<td>-5035.4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th">LLR p-value:</td>
<td>0.001696</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">z</td>
<td data-quarto-table-cell-role="th">P&gt;|z|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>-2.1001</td>
<td>0.023</td>
<td>-90.073</td>
<td>0.000</td>
<td>-2.146</td>
<td>-2.054</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">treatment</td>
<td>0.0868</td>
<td>0.028</td>
<td>3.113</td>
<td>0.002</td>
<td>0.032</td>
<td>0.141</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="interpretation-of-experimental-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-experimental-results">Interpretation of Experimental Results</h3>
<p>The evidence suggests that being assigned to the treatment group — receiving a matching donation offer — significantly increased the likelihood of making a charitable donation.</p>
<ul>
<li>The <strong>bar plot</strong> shows a noticeable difference in donation rates between the treatment and control groups.</li>
<li>The <strong>t-test</strong> reveals a statistically significant difference in donation behavior (T = 3.209, p = 0.001), meaning the treatment group donated at a higher rate than the control group.</li>
<li>The <strong>OLS regression</strong> confirms this finding. The treatment coefficient is <strong>0.0042</strong>, with a p-value of <strong>0.002</strong>, indicating that assignment to treatment increases the probability of donating by about 0.42 percentage points.</li>
<li>The <strong>Probit regression</strong> also supports this: the coefficient on treatment is <strong>0.0868</strong> (p = 0.002), again showing a positive and statistically significant effect on the likelihood of giving.</li>
</ul>
<p>Overall, these results replicate the findings in Karlan and List (2007): <strong>matching donations increase the probability of giving</strong>, even if the actual increase is modest in absolute terms. The consistency across all three statistical approaches (t-test, OLS, and probit) strengthens the causal interpretation of the results. This supports the idea that even small nudges like matching offers can influence donor behavior.</p>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
</section>
<section id="differences-between-match-rates-1" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates-1">Differences between Match Rates</h3>
<p>We explore whether larger match ratios (e.g., 2:1 or 3:1) result in higher likelihoods of donating compared to a 1:1 match.</p>
<hr>
</section>
<section id="t-tests-for-match-ratios" class="level3">
<h3 class="anchored" data-anchor-id="t-tests-for-match-ratios">T-tests for Match Ratios</h3>
<div id="5764ca73" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter only treatment group and each match ratio</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ratio1 <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>)][<span class="st">'gave'</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>ratio2 <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>)][<span class="st">'gave'</span>]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>ratio3 <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>)][<span class="st">'gave'</span>]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># T-tests</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"2:1 vs 1:1"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.ttest_ind(ratio2, ratio1, equal_var<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">3:1 vs 2:1"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.ttest_ind(ratio3, ratio2, equal_var<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2:1 vs 1:1
TtestResult(statistic=0.965048975142932, pvalue=0.33453078237183076, df=22225.07770983836)

3:1 vs 2:1
TtestResult(statistic=0.05011581369764474, pvalue=0.9600305476940865, df=22260.84918918778)</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Interpretation</strong>:<br>
These t-tests compare donation rates for each match ratio within the treatment group.<br>
- The <strong>2:1 vs 1:1</strong> test shows a [insert p-value here], and<br>
- The <strong>3:1 vs 2:1</strong> test shows a [insert p-value here].</p>
<p>In both comparisons, the p-values are relatively large, suggesting <strong>no statistically significant difference</strong> in donation likelihood across match sizes. This supports Karlan and List’s finding that <strong>increasing the match ratio does not meaningfully improve the effectiveness of the match offer.</strong></p>
</blockquote>
<hr>
</section>
<section id="regression-on-match-ratio-categorical" class="level3">
<h3 class="anchored" data-anchor-id="regression-on-match-ratio-categorical">Regression on Match Ratio (Categorical)</h3>
<div id="f3b69ca4" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for treatment group and valid match ratios</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>match_data <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>].isin([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]))].copy()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Properly set 'ratio' as a categorical variable with 1:1 as the baseline</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>match_data[<span class="st">'ratio'</span>] <span class="op">=</span> pd.Categorical(match_data[<span class="st">'ratio'</span>], categories<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the regression: donation behavior by match ratio</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> smf.ols(<span class="st">"gave ~ C(ratio)"</span>, data<span class="op">=</span>match_data).fit()</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>model.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>gave</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>-0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>0.6454</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.524</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:39:02</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>16688.</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>33396</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>-3.337e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>33393</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>-3.334e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>2</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>0.0207</td>
<td>0.001</td>
<td>14.912</td>
<td>0.000</td>
<td>0.018</td>
<td>0.023</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">C(ratio)[T.2]</td>
<td>0.0019</td>
<td>0.002</td>
<td>0.958</td>
<td>0.338</td>
<td>-0.002</td>
<td>0.006</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">C(ratio)[T.3]</td>
<td>0.0020</td>
<td>0.002</td>
<td>1.008</td>
<td>0.313</td>
<td>-0.002</td>
<td>0.006</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>38963.957</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>1.995</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.000</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>2506478.937</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>6.511</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>43.394</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>3.73</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<blockquote class="blockquote">
<p><strong>Interpretation</strong>:<br>
The regression estimates donation rates for each match ratio using the 1:1 match as the baseline (intercept = 2.07%).<br>
- The coefficient for <code>2:1</code> is <strong>0.0019</strong> (p = 0.338), and<br>
- The coefficient for <code>3:1</code> is <strong>0.0020</strong> (p = 0.313).</p>
<p>These coefficients are very small and <strong>not statistically significant</strong>, indicating that <strong>higher match ratios do not meaningfully increase the likelihood of giving</strong> beyond what is achieved with a 1:1 match.</p>
<p>This supports the key finding in Karlan and List (2007): the <strong>existence</strong> of a match offer increases donations, but <strong>increasing the ratio</strong> (e.g., from 1:1 to 3:1) <strong>does not further boost effectiveness</strong>.</p>
</blockquote>
<hr>
<section id="response-rate-differences-from-raw-data-and-model" class="level4">
<h4 class="anchored" data-anchor-id="response-rate-differences-from-raw-data-and-model">Response Rate Differences from Raw Data and Model</h4>
<div id="e8a85a1f" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group-level mean donation rates</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ratio1 <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">1</span>)][<span class="st">'gave'</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>ratio2 <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">2</span>)][<span class="st">'gave'</span>]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>ratio3 <span class="op">=</span> data[(data[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (data[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="dv">3</span>)][<span class="st">'gave'</span>]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>mean1 <span class="op">=</span> ratio1.mean()</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>mean2 <span class="op">=</span> ratio2.mean()</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>mean3 <span class="op">=</span> ratio3.mean()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Response Rate 1:1 = </span><span class="sc">{</span>mean1<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Response Rate 2:1 = </span><span class="sc">{</span>mean2<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Response Rate 3:1 = </span><span class="sc">{</span>mean3<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">2:1 - 1:1 = </span><span class="sc">{</span>mean2 <span class="op">-</span> mean1<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 - 2:1 = </span><span class="sc">{</span>mean3 <span class="op">-</span> mean2<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response Rate 1:1 = 0.0207
Response Rate 2:1 = 0.0226
Response Rate 3:1 = 0.0227

2:1 - 1:1 = 0.0019
3:1 - 2:1 = 0.0001</code></pre>
</div>
</div>
<div id="2c024b94" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model-based differences from regression coefficients</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>coef <span class="op">=</span> model.params</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Model-Based Differences:"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"2:1 - 1:1 = </span><span class="sc">{</span>coef[<span class="st">'C(ratio)[T.2]'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 - 1:1 = </span><span class="sc">{</span>coef[<span class="st">'C(ratio)[T.3]'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"3:1 - 2:1 = </span><span class="sc">{</span>coef[<span class="st">'C(ratio)[T.3]'</span>] <span class="op">-</span> coef[<span class="st">'C(ratio)[T.2]'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Model-Based Differences:
2:1 - 1:1 = 0.0019
3:1 - 1:1 = 0.0020
3:1 - 2:1 = 0.0001</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Interpretation</strong>:<br>
Both the raw response rate differences and the model-based regression estimates suggest that increasing the match ratio from <strong>1:1 to 2:1</strong> leads to a very small increase in the probability of giving (approximately <strong>0.0019</strong>, or 0.19 percentage points).</p>
<p>Increasing the ratio further from <strong>2:1 to 3:1</strong> adds virtually no additional effect — a difference of just <strong>0.0001</strong>, or 0.01 percentage points. These differences are not only small in magnitude but also statistically insignificant based on earlier t-tests and regression outputs.</p>
<p>The fact that the <strong>raw differences</strong> and <strong>regression coefficients</strong> are nearly identical provides strong evidence that these small effects are consistent across estimation approaches.</p>
<p>In line with Karlan and List (2007), we conclude that <strong>the presence of a match offer matters</strong>, but <strong>larger match ratios (like 3:1) do not provide additional benefit</strong> over a standard 1:1 match. This supports their interpretation that psychological or motivational factors may be triggered by any match, not necessarily a more generous one.</p>
</blockquote>
<hr>
</section>
</section>
<section id="summary" class="level3">
<h3 class="anchored" data-anchor-id="summary">Summary</h3>
<div class="callout callout-style-simple callout-note no-icon callout-titled" title="Conclusion">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Conclusion
</div>
</div>
<div class="callout-body-container callout-body">
<p>Neither the t-tests nor the regression provide strong evidence that increasing the match ratio from 1:1 to 2:1 or 3:1 significantly increases the donation response rate. The estimated differences are small and statistically insignificant. These findings replicate Karlan and List’s claim on page 8 that “larger match ratios do not provide additional lift,” and suggest that announcing any match offer may be sufficient to nudge donation behavior — but increasing the ratio adds little extra power.</p>
</div>
</div>
</section>
</section>
<section id="size-of-charitable-contribution" class="level2">
<h2 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h2>
<p>In this subsection, I analyze the effect of the matching donation offer on the <strong>amount donated</strong>, not just whether individuals gave. I examine this in two ways: (1) using the full sample including non-donors, and (2) restricting the analysis to only those who made a donation.</p>
<hr>
<section id="full-sample-regression" class="level3">
<h3 class="anchored" data-anchor-id="full-sample-regression">Full Sample Regression</h3>
<p>The first model regresses the donation amount (<code>amount</code>) on the treatment assignment across the entire sample, including non-donors (who are coded as 0 for amount). This allows us to assess the <strong>average treatment effect</strong> on giving across all individuals.</p>
<div id="3601d604" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display" data-execution_count="12">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>amount</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>3.461</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.0628</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:39:02</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-1.7946e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>50083</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>3.589e+05</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>50081</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>3.589e+05</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>1</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>0.8133</td>
<td>0.067</td>
<td>12.063</td>
<td>0.000</td>
<td>0.681</td>
<td>0.945</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">treatment</td>
<td>0.1536</td>
<td>0.083</td>
<td>1.861</td>
<td>0.063</td>
<td>-0.008</td>
<td>0.315</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>96861.113</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>2.008</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.000</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>240735713.635</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>15.297</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>341.269</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>3.23</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<p>The regression results show that the <strong>intercept</strong> (average donation in the control group) is <strong>$0.8133</strong>, while the treatment effect is estimated at <strong>$0.1536</strong>. The p-value for the treatment coefficient is <strong>0.063</strong>, which is <strong>marginally significant</strong> at the 10% level.</p>
<p>This suggests that receiving a matching offer may lead to a small increase in the average donation amount across the full sample, but the evidence is not strong enough to be statistically significant at conventional 5% thresholds.</p>
<hr>
</section>
<section id="regression-among-donors-only" class="level3">
<h3 class="anchored" data-anchor-id="regression-among-donors-only">Regression Among Donors Only</h3>
<p>Next, I restrict the sample to individuals who actually made a donation (<code>gave == 1</code>) to test whether the matching offer affected <strong>how much donors gave</strong>, conditional on donating.</p>
<div id="948d1495" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display" data-execution_count="13">
<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<caption>OLS Regression Results</caption>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Dep. Variable:</td>
<td>amount</td>
<td data-quarto-table-cell-role="th">R-squared:</td>
<td>0.000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Model:</td>
<td>OLS</td>
<td data-quarto-table-cell-role="th">Adj. R-squared:</td>
<td>-0.001</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Method:</td>
<td>Least Squares</td>
<td data-quarto-table-cell-role="th">F-statistic:</td>
<td>0.3374</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Date:</td>
<td>Wed, 07 May 2025</td>
<td data-quarto-table-cell-role="th">Prob (F-statistic):</td>
<td>0.561</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Time:</td>
<td>21:39:02</td>
<td data-quarto-table-cell-role="th">Log-Likelihood:</td>
<td>-5326.8</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">No. Observations:</td>
<td>1034</td>
<td data-quarto-table-cell-role="th">AIC:</td>
<td>1.066e+04</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Df Residuals:</td>
<td>1032</td>
<td data-quarto-table-cell-role="th">BIC:</td>
<td>1.067e+04</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Df Model:</td>
<td>1</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Covariance Type:</td>
<td>nonrobust</td>
<td data-quarto-table-cell-role="th"></td>
<td></td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">coef</td>
<td data-quarto-table-cell-role="th">std err</td>
<td data-quarto-table-cell-role="th">t</td>
<td data-quarto-table-cell-role="th">P&gt;|t|</td>
<td data-quarto-table-cell-role="th">[0.025</td>
<td data-quarto-table-cell-role="th">0.975]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Intercept</td>
<td>45.5403</td>
<td>2.423</td>
<td>18.792</td>
<td>0.000</td>
<td>40.785</td>
<td>50.296</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">treatment</td>
<td>-1.6684</td>
<td>2.872</td>
<td>-0.581</td>
<td>0.561</td>
<td>-7.305</td>
<td>3.968</td>
</tr>
</tbody>
</table>


<table class="simpletable caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">Omnibus:</td>
<td>587.258</td>
<td data-quarto-table-cell-role="th">Durbin-Watson:</td>
<td>2.031</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Prob(Omnibus):</td>
<td>0.000</td>
<td data-quarto-table-cell-role="th">Jarque-Bera (JB):</td>
<td>5623.279</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">Skew:</td>
<td>2.464</td>
<td data-quarto-table-cell-role="th">Prob(JB):</td>
<td>0.00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">Kurtosis:</td>
<td>13.307</td>
<td data-quarto-table-cell-role="th">Cond. No.</td>
<td>3.49</td>
</tr>
</tbody>
</table>
<br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<p>Among donors, the <strong>average donation in the control group</strong> is approximately <strong>$45.54</strong>, as reflected in the intercept. The treatment group gave on average <strong>$1.67 less</strong> than the control group, though this difference is <strong>not statistically significant</strong> (p = <strong>0.561</strong>).</p>
<hr>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<p>These results indicate that while the treatment may increase the <strong>likelihood</strong> of giving (as seen earlier), it does <strong>not significantly affect the amount donated</strong>. In the full sample, the treatment effect is small and only marginally significant. Among those who donated, the estimated effect is negative and clearly not statistically significant.</p>
<p>Because the treatment was randomly assigned, the coefficient estimates can be interpreted causally. However, it is important to note that the donor-only model is conditional on post-treatment behavior and may be affected by selection.</p>
<p>Overall, this analysis supports the main takeaway from Karlan and List (2007): <strong>matching offers increase participation (extensive margin), but not the size of contributions (intensive margin)</strong>.</p>
<section id="histogram-of-donation-amounts-treatment-group" class="level4">
<h4 class="anchored" data-anchor-id="histogram-of-donation-amounts-treatment-group">Histogram of Donation Amounts: Treatment Group</h4>
<div id="f753f90c" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions (4)_files/figure-html/cell-15-output-1.png" width="593" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="histogram-of-donation-amounts-control-group" class="level4">
<h4 class="anchored" data-anchor-id="histogram-of-donation-amounts-control-group">Histogram of Donation Amounts: Control Group</h4>
<div id="ccd8c353" class="cell" data-message="false" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions (4)_files/figure-html/cell-16-output-1.png" width="585" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">Interpretation</h3>
<blockquote class="blockquote">
<p>In the regression using the full sample, we find that the treatment group donated $0.15 more on average than the control group. However, this result is not statistically significant (p = 0.063), meaning we cannot rule out that the difference is due to random chance.</p>
<p>In the donor-only regression, we isolate just the people who made a donation and ask: do those in the treatment group give more than those in the control? Here, the treatment coefficient is -1.67, again not statistically significant (p = 0.561). In fact, the sign of the effect is slightly negative.</p>
<p>The histograms show that donation amounts are heavily skewed, with most donations under $100. The means for treatment and control are both around $45–46, with very similar distributions.</p>
<p>Conclusion: The treatment (i.e., receiving a matching offer) appears to influence whether people give, but not how much they give. The full-sample regression can be interpreted causally because of random assignment, while the donor-only regression cannot, since it conditions on a post-treatment behavior (selection bias).</p>
<p>Overall, our findings replicate Karlan and List (2007): matching gifts increase response rates, but do not significantly affect the donation size conditional on giving.</p>
</blockquote>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<p>We simulate two large samples: - One from the control group (donation probability = 0.018) - One from the treatment group (donation probability = 0.022)</p>
<p>We calculate the difference between matched pairs, and then compute the cumulative average difference.</p>
</section>
<section id="law-of-large-numbers-1" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers-1">Law of Large Numbers</h3>
<p>To illustrate the Law of Large Numbers, I simulate two groups: one representing respondents who did not receive a matching donation offer (control, with donation probability ( p = 0.018 )), and one representing those who did (treatment, with ( p = 0.022 )). I draw 10,000 samples from each group and compute the difference for each pair. Then, I calculate and plot the <strong>cumulative average</strong> of these differences.</p>
</section>
<section id="law-of-large-numbers-2" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers-2">Law of Large Numbers</h3>
<p>To illustrate the Law of Large Numbers, I simulate two groups: one representing respondents who did not receive a matching donation offer (control, with donation probability ( p = 0.018 )), and one representing those who did (treatment, with ( p = 0.022 )). I draw 10,000 samples from each group and compute the difference for each pair. Then, I calculate and plot the <strong>cumulative average</strong> of these differences.</p>
</section>
<section id="law-of-large-numbers-3" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers-3">Law of Large Numbers</h3>
<p>To simulate the Law of Large Numbers, I compare paired random samples from two Bernoulli distributions: one for the control group (( p = 0.018 )) and one for the treatment group (( p = 0.022 )). I compute the difference in outcomes for each pair and plot the cumulative average to see whether it converges to the true mean difference of 0.004.</p>
</section>
<section id="law-of-large-numbers-convergence-of-mean-difference" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers-convergence-of-mean-difference">Law of Large Numbers: Convergence of Mean Difference</h3>
<div id="25a785fb" class="cell" data-message="false" data-execution_count="16">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions (4)_files/figure-html/cell-17-output-1.png" width="697" height="388" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As shown in the plot above, the cumulative average of the differences fluctuates at first but gradually stabilizes around the true expected difference of <strong>0.004</strong>. This pattern exemplifies the <strong>Law of Large Numbers</strong>, which states that as the number of observations increases, the sample average converges to the population mean.</p>
<p>This visualization demonstrates that even with a small true effect size, a sufficiently large number of observations can reveal consistent patterns. It provides a conceptual foundation for why the original Karlan and List experiment, which involved tens of thousands of letters, was able to detect subtle differences in donation behavior.</p>
<p>As shown in the plot above, the cumulative average of the differences fluctuates at first but gradually stabilizes around the true expected difference of <strong>0.004</strong>. This pattern exemplifies the <strong>Law of Large Numbers</strong>, which states that as the number of observations increases, the sample average converges to the population mean.</p>
<p>This visualization demonstrates that even with a small true effect size, a sufficiently large number of observations can reveal consistent patterns. It provides a conceptual foundation for why the original Karlan and List experiment, which involved tens of thousands of letters, was able to detect subtle differences in donation behavior.</p>
<hr>
</section>
<section id="interpretation-3" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-3">Interpretation</h3>
<blockquote class="blockquote">
<p>The simulation demonstrates the <strong>Law of Large Numbers</strong>, which states that as the number of observations increases, the sample average converges to the population mean.</p>
<p>In this plot, the cumulative average difference in donation rates between the treatment (p = 0.022) and control (p = 0.018) groups begins with wide fluctuations due to randomness in the early observations. However, as we simulate more and more matched pairs (up to 100,000), the cumulative difference stabilizes and converges to the true expected difference of <strong>0.004</strong>.</p>
<p>This reinforces a key idea in statistics: <strong>with large enough sample sizes, the law of averages ensures reliable estimates of population parameters</strong>. It also explains why Karlan and List were able to detect small treatment effects — because their experiment had tens of thousands of observations. ```</p>
</blockquote>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<p>We simulate distributions of average differences in donation rates between control (p = 0.018) and treatment (p = 0.022) groups, using increasing sample sizes (n = 50, 200, 500, 1000). For each sample size, we repeat the process 1000 times and visualize the distribution of sample differences.</p>
<div id="fa77ef88" class="cell" data-message="false" data-execution_count="17">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw1_questions (4)_files/figure-html/cell-18-output-1.png" width="946" height="627" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
<section id="interpretation-4" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-4">Interpretation</h3>
<blockquote class="blockquote">
<p>These four histograms illustrate the <strong>Central Limit Theorem</strong> using simulated sample means of donation rate differences between the treatment (p = 0.022) and control (p = 0.018) groups.</p>
<p>As the sample size increases: - With <strong>n = 50</strong>, the distribution is wide and noisy — there’s considerable variation, and the true mean difference (0.004) is not clearly distinguishable from zero. - At <strong>n = 200</strong>, the distribution begins to resemble a bell curve, and the true difference is more centered. - At <strong>n = 500</strong>, the histogram tightens noticeably, and zero begins to lie closer to the tail of the distribution. - By <strong>n = 1000</strong>, the sample mean differences are tightly clustered around 0.004, and <strong>zero is clearly no longer at the center</strong> — it lies in the tail, suggesting strong evidence against the null of no effect.</p>
<p>This simulation confirms that <strong>larger samples reduce sampling variability</strong> and make it easier to detect small, true differences — exactly what Karlan and List leveraged with their large-scale experiment.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>